In [97]:
import torch

## 创建Tensor

In [98]:
x = torch.empty(5,3 )
x

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38]])

In [99]:
x = torch.rand(5,3)
x

tensor([[0.2571, 0.9962, 0.8571],
        [0.3346, 0.8726, 0.3357],
        [0.5182, 0.6966, 0.9014],
        [0.4326, 0.6427, 0.4632],
        [0.6361, 0.7085, 0.7102]])

In [100]:
x = torch.zeros(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [101]:
## 利用数据直接创建tensor
x = torch.tensor([5,3.12])
x

tensor([5.0000, 3.1200])

In [102]:
## 利用现有的tensor创建
x = x.new_ones(5,3,dtype = torch.float64)
# 返回的tensor默认具有相同的torch.dtype和torch.device
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [103]:
x = torch.rand_like(x,dtype=torch.float)
# 指定新的数据类型
# 得到的x为：
x

tensor([[0.0767, 0.6980, 0.0975],
        [0.6155, 0.6210, 0.8214],
        [0.5777, 0.8027, 0.8495],
        [0.8829, 0.8128, 0.3718],
        [0.0642, 0.7981, 0.2649]])

In [104]:
# 获取tensor的shape或者数据类型
x.shape
#  返回的torch.Size是一个tuple, 支持所有tuple的操作。

torch.Size([5, 3])

In [105]:
# 获取tensor的数据类型
x.dtype

torch.float32

## 算数操作 : **两个 Tensor 进行加减乘除算术操作时会自动进行Broadcasting。**

In [106]:
## 加法运算
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[1,1,1],[1,1,1]])
torch.add(x,y)

tensor([[2, 3, 4],
        [5, 6, 7]])

In [107]:
## 减法运算
torch.sub(y,x)

tensor([[ 0, -1, -2],
        [-3, -4, -5]])

In [108]:
## 乘法运算： 对应元素相乘
torch.mul(torch.mul(x,y),torch.mul(x,y))

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [109]:
## 除法运算
torch.div(torch.mul(x,y),torch.mul(x,y))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [110]:
## 叉乘（矩阵相乘）
x = torch.tensor(x,dtype=float)
x

C:\Users\34225\AppData\Local\Temp\ipykernel_16032\975640294.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x,dtype=float)


tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [111]:
y = torch.tensor(y,dtype=float)
y = y.reshape(3,2)

C:\Users\34225\AppData\Local\Temp\ipykernel_16032\3014323749.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y,dtype=float)


In [114]:
z = torch.mm(x,y)
z

tensor([[ 6.,  6.],
        [15., 15.]], dtype=torch.float64)

**定义其矩阵乘法仅在最后的两个维度上，要求前面的维度必须保持一致**

In [117]:
## 对数运算
torch.log(z)

tensor([[1.7918, 1.7918],
        [2.7081, 2.7081]], dtype=torch.float64)

## 改变形状

In [119]:
## 使用view函数来改变形状
z = z.view(-1,4)
z
## 注意这里的-1标注的维度可以根据其他的维度进行推断该维度的长度

tensor([[ 6.,  6., 15., 15.]], dtype=torch.float64)

In [120]:
b = x.clone()
b

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [123]:
## 通过item将tensor中的元素转换为number
b[0,1].item()

2.0

 ## 还支持一些线性代数函数：如奇异值分解（svd）、逆矩阵、内积/外积、转置等

## 当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算。

**tensor可以直接转为numpy，当然numpy也可以转为tensor**

In [126]:
c = x.numpy()
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [128]:
d = torch.from_numpy(c)
d

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

## 在GPU上的一些操作
**用方法to()可以将Tensor在CPU和GPU（需要硬件支持）之间相互移动。**

In [129]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接创建一个在GPU上的Tensor
    x = x.to(device)                       # 等价于 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()还可以同时更改数据类型

tensor([[2., 3., 4.],
        [5., 6., 7.]], device='cuda:0', dtype=torch.float64)
tensor([[2., 3., 4.],
        [5., 6., 7.]], dtype=torch.float64)


In [131]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
x = torch.tensor([1,1,1,1],dtype=torch.float64, device =device)
x

tensor([1., 1., 1., 1.], device='cuda:0', dtype=torch.float64)